fail_fast: true
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [ --fix=lf ]
    -   id: debug-statements
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        args:
            - --exclude=/(tests)/
            - --line-length=120
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        args:
            - --ignore-words-list=nin
            - --skip=poetry.lock
-   repo: https://github.com/PyCQA/prospector
    rev: 6ee6cd97b78ebdd8d131ae601c422471cd3a3fd2
    hooks:
    -   id: prospector
        additional_dependencies:
            - '.[with_everything]'
            # the following are needed to run mypy successfully in the pre-commit virtualenv
            - types-setuptools
            - types-PyYAML
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
