output-format: grouped

inherits:
  - strictness_veryhigh

ignore:
  - ^docs/

dodgy:
    run: true

mccabe:
    run: true

pep257:
    run: true

pyflakes:
    run: true

frosted:
    run: true

vulture:
    run: true

pyroma:
  run: true

pylint:
  options:
    max-line-length: 120

pep8:
  options:
    max-line-length: 120
