output-format: grouped

strictness: veryhigh
doc-warnings: no
test-warnings: no
max-line-length: 120
pep8: full

ignore-paths:
  - docs/

frosted:
  run: false

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip

pylint:
  disable:
    - too-few-public-methods
    - missing-docstring
    - star-args
    - consider-using-f-string

pycodestyle:
  disable:
    - E126

pydocstyle:
  run: false
  disable:
    - D100
    - D101
    - D102
    - D103
    - D107
    - D205
    - D400
    - D401
