output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: false
max-line-length: 120

ignore-paths:
  - docs/

frosted:
  run: false

mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip

pylint:
  disable:
    - bad-builtin
    - too-few-public-methods
    - missing-docstring
    - star-args

pep8: full

pycodestyle:
  disable:
    - E126

pydocstyle:
  run: false
  disable:
    - D100
    - D101
    - D102
    - D103
    - D107
    - D205
    - D400
    - D401
