language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - "pip install nose coverage coveralls mock"
  - "pip install --editable ."
script:
  - "nosetests -s --with-coverage --cover-inclusive --cover-package=prospector tests/"
  - "mv .coverage .coverage.x"
  - "pip install -e .[with_everything]"
  - "coverage run --parallel-mode prospector/run.py || true"
  - "coverage combine"
  - "coverage report --show-missing"
after_success:
  - |
      prospector -0
      coveralls
notifications:
  email:
    on_failure: change
    on_success: never
