language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --use-mirrors nose"
  - "pip install git+https://github.com/landscapeio/pylint-plugin-utils.git@develop"
  - "pip install git+https://github.com/landscapeio/pylint-common.git@develop"
  - "pip install git+https://github.com/landscapeio/pylint-celery.git@develop"
  - "pip install git+https://github.com/landscapeio/pylint-django.git@develop"
  - "pip install git+https://github.com/landscapeio/requirements-detector.git@develop"
  - "pip install --use-mirrors --editable ."
script: nosetests -s
